import { Customer } from "../../models/customer.model";

 export const customers: Customer[] = [
    {
        id: 1,
        name: 'duaa khaled',
        phone: '0791234567',
        email: 'duaa@gmail.com',
        address: 'Amman, Jordan',
      },
      {
        id: 2,
        name: 'Lina Haddad',
        phone: '0789876543',
        email: 'yousef25@gmail.com', 
        address: 'Irbid, Jordan',
      },
      {
        id: 3,
        name: 'Omar Salem',
        phone: '0775551212',
        email: 'omar.salem@gmail.com',
        address: 'Zarqa, Jordan',
      },
      {
        id: 4,
        name: 'Nour Khalil',
        phone: '0793334455',
        email: 'nour.khalil@gmail.com',
        address: 'Aqaba, Jordan',
      },
      {
        id: 5,
        name: 'reema',
        phone: '0781122334',
        email: 'reema2@gmail.com',
        address: 'Madaba, Jordan',
      },
      {
        id: 6,
        name: 'Rania Ali',
        phone: '0776677889',
        email: 'rania.ali@gmail.com',
        address: 'Salt, Jordan',
      },

       {
        id: 7,
        name: 'duaa khaled',
        phone: '0791234567',
        email: 'duaa1@gmail.com',
        address: 'Amman, Jordan',
      },
      {
        id: 8,
        name: 'Lina Haddad',
        phone: '0789876543',
        email: 'yousef2@gmail.com', 
        address: 'Irbid, Jordan',
      },
      {
        id: 9,
        name: 'Omar Salem',
        phone: '0775551212',
        email: 'omar.salem1@gmail.com',
        address: 'Zarqa, Jordan',
      },
      {
        id: 10,
        name: 'Nour Khalil',
        phone: '0793334455',
        email: 'nour.khalil1@gmail.com',
        address: 'Aqaba, Jordan',
      },
      {
        id: 11,
        name: 'reema',
        phone: '0781122334',
        email: 'reema3@gmail.com',
        address: 'Madaba, Jordan',
      },
      {
        id: 12,
        name: 'Rania Ali',
        phone: '0776677889',
        email: 'rania.ali1@gmail.com',
        address: 'Salt, Jordan',
      },
       {
        id: 13,
        name: 'duaa khaled',
        phone: '0791234567',
        email: 'duaa5@gmail.com',
        address: 'Amman, Jordan',
      },
      {
        id: 14,
        name: 'Lina Haddad',
        phone: '0789876543',
        email: 'yousef78@gmail.com', 
        address: 'Irbid, Jordan',
      },
      {
        id: 15,
        name: 'Omar Salem',
        phone: '0775551212',
        email: 'omar.salem12@gmail.com',
        address: 'Zarqa, Jordan',
      },
      {
        id: 16,
        name: 'Nour Khalil',
        phone: '0793334455',
        email: 'nour.khalil16@gmail.com',
        address: 'Aqaba, Jordan',
      },
      {
        id: 17,
        name: 'reema',
        phone: '0781122334',
        email: 'reema87@gmail.com',
        address: 'Madaba, Jordan',
      },
      {
        id: 18,
        name: 'Rania Ali',
        phone: '0776677889',
        email: 'rania.ali88@gmail.com',
        address: 'Salt, Jordan',
      },
      {
        id: 19,
        name: 'Anagheem ALRabaa',
        phone: '0776677889',
        email: 'anagheem@gmail.com',
        address: 'Irbed, Jordan',
      },
      {
        id: 20,
        name: 'Mohammed Alaa',
        phone: '0791245698',
        email: 'mohammed@gmail.com',
        address: 'Amman, Jordan',
      },
];