import { RoomAppointment } from "../../models/room-appointment.model";

export const roomAppointments: RoomAppointment[] = [
    {
        id: 1,
        date: '2023-10-27T10:00:00Z',
        customerId: 1,
        approvalStatus: 'approved',
        paymentStatus: true,
        paymentAmount: 250,
      },
      {
        id: 2,
        date: '2023-11-15T14:30:00Z',
        customerId: 2,
        approvalStatus: 'pending',
        paymentStatus: false,
        paymentAmount: 500,
      },
      {
        id: 3,
        date: '2023-12-01T09:00:00Z',
        customerId: 3,
        approvalStatus: 'rejected',
        paymentStatus: false,
        paymentAmount: 100,
      },
      {
        id: 4,
        date: '2023-11-20T18:00:00Z',
        customerId: 4,
        approvalStatus: 'approved',
        paymentStatus: true,
        paymentAmount: 300,
      },
      {
        id: 5,
        date: '2023-12-25T12:00:00Z',
        customerId: 5,
        approvalStatus: 'pending',
        paymentStatus: false,
        paymentAmount: 750,
      },
      {
        id: 6,
        date: '2024-01-10T16:00:00Z',
        customerId: 5,
        approvalStatus: 'approved',
        paymentStatus: true,
        paymentAmount: 400,
      },
      {
        id: 7,
        date: '2024-02-12T11:00:00Z',
        customerId: 1,
        approvalStatus: 'rejected',
        paymentStatus: false,
        paymentAmount: 200,
      },
      {
        id: 8,
        date: '2024-02-18T09:30:00Z',
        customerId: 2,
        approvalStatus: 'approved',
        paymentStatus: true,
        paymentAmount: 350,
      },
      {
        id: 9,
        date: '2024-03-01T13:00:00Z',
        customerId: 3,
        approvalStatus: 'pending',
        paymentStatus: false,
        paymentAmount: 275,
      },
      {
        id: 10,
        date: '2024-03-10T15:45:00Z',
        customerId: 4,
        approvalStatus: 'approved',
        paymentStatus: true,
        paymentAmount: 500,
      },
      {
        id: 11,
        date: '2024-03-15T14:00:00Z',
        customerId: 1,
        approvalStatus: 'pending',
        paymentStatus: false,
        paymentAmount: 450,
      },
      {
        id: 12,
        date: '2024-03-20T17:30:00Z',
        customerId: 2,
        approvalStatus: 'rejected',
        paymentStatus: false,
        paymentAmount: 150,
      },
      {
        id: 13,
        date: '2024-04-01T08:00:00Z',
        customerId: 3,
        approvalStatus: 'approved',
        paymentStatus: true,
        paymentAmount: 600,
      },
      {
        id: 14,
        date: '2024-04-10T10:20:00Z',
        customerId: 4,
        approvalStatus: 'pending',
        paymentStatus: false,
        paymentAmount: 120,
      },
      {
        id: 15,
        date: '2024-04-15T11:15:00Z',
        customerId: 5,
        approvalStatus: 'rejected',
        paymentStatus: false,
        paymentAmount: 90,
      }
];
